// Automatically generated by MockGen. DO NOT EDIT!
// Source: checker.go

package mock_mimechecker

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Checker interface
type MockChecker struct {
	ctrl     *gomock.Controller
	recorder *_MockCheckerRecorder
}

// Recorder for MockChecker (not exported)
type _MockCheckerRecorder struct {
	mock *MockChecker
}

func NewMockChecker(ctrl *gomock.Controller) *MockChecker {
	mock := &MockChecker{ctrl: ctrl}
	mock.recorder = &_MockCheckerRecorder{mock}
	return mock
}

func (_m *MockChecker) EXPECT() *_MockCheckerRecorder {
	return _m.recorder
}

func (_m *MockChecker) TypeByFile(path string) (string, error) {
	ret := _m.ctrl.Call(_m, "TypeByFile", path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockCheckerRecorder) TypeByFile(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "TypeByFile", arg0)
}
